import type { Metadata } from "next";
import "./globals.css";
import Header from "@/section/Header";
import Footer from "@/section/Footer";
import Chatbot from "@/components/Chatbot";

export const metadata: Metadata = {
  title: "Scholar: Knowledge Without Limits",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/logo.png" />
      </head>
      <body className="antialiased">
        <Header />
        {children}
        <Chatbot />
        <Footer />
      </body>
    </html>
  );
}
